version: '3.9'

services:
  building-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: building-service-dev
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_BROKER: ${KAFKA_BROKER}
      KAFKA_CLIENT_ID: ${KAFKA_CLIENT_ID}
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      UPLOAD_SERVICE_URL: ${UPLOAD_SERVICE_URL}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npm run start:dev"
    networks:
      my_custom_network:
        ipv4_address: ${APP_IP}

networks:
  my_custom_network:
    external: true

